<!DOCTYPE html>
<html lang="en">

<head>
	<title>SSI Cables</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="html 5 template">

	<link rel="icon" href="SSI_cables_icon.png">
	<!-- Bootstrap core CSS -->
	<link href="css/plugins/bootstrap.min.css" rel="stylesheet">
	<link href="css/plugins/bootstrap-submenu.css" rel="stylesheet">
	<link href="css/plugins/bootstrap-datetimepicker.css" rel="stylesheet">
	<link href="css/plugins/animate.min.css" rel="stylesheet">
	<link href="css/plugins/nivo-slider.css" rel="stylesheet">
	<link href="css/plugins/slick.css" rel="stylesheet">
	<link href="css/plugins/magnific-popup.css" rel="stylesheet">
	<link href="css/custom.css" rel="stylesheet">
	<link href="css/mega-menu.css" rel="stylesheet">
	<!-- Icon Font-->
	<link href="iconfont/style.css" rel="stylesheet">
	<!-- Google Fonts -->

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-174541765-2"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'UA-174541765-2');
	</script>


	<?php $page = 3;
	include('header.php'); ?>

	<!-- // Header -->

	<!-- Content  -->

	<div id="page-content">
        <div class="block">
            <div class="row">
                <div class="col-md-12 col-lg-12">

					<div class="category-text">

						<div class="category-image">
                            <img src="images/headers/dc cable.jpg" class="img-responsive" alt="Best Coated Wire Manufacturer">
                        </div>

						<br />
                    </div>
                    <div class="container" style="border:1px solid black; padding:17px 27px; box-shadow: 10px 10px 5px #888888;">

                        <div class="row">

							<div class="col-md-12">
								<h1 style="font-size: 25px;color:#f47629;">DC Cables</h1>
                                
								<hr />
								<p style="text-align:justify">
                                <b>DC cables</b> manufactured by SSI Cables have the following characteristics.
								 The DC cables manufactured by SSI Cables and Wires are used in the rectified 
								 DC transmission system. The power loss during the transmission of the DC 
								 cable is small. The power loss of the DC cable is mainly the DC resistance
								  loss of the conductor, and the insulation loss is small (the size depends 
								  on the current fluctuation after rectification). The AC resistance of the
								   low-voltage AC cable is slightly larger than the DC resistance,
								    the high-voltage cable is obvious, mainly because of The proximity effect
									 and the skin effect, the loss of insulation resistance accounts for a 
									 large proportion, mainly the impedance generated by the capacitor and
									  the inductor. High transmission efficiency and low line loss. It is
									   convenient to adjust the current and change the power transmission 
									   direction. Although the price of the converter equipment is higher
									    than that of the transformer, the cost of using the cable line is 
										much lower than that of the AC cable. The DC cable is positive and 
										negative poles, and the structure is simple. The AC cable is a 
										three-phase four-wire or five-wire system, the insulation safety
										 requirements are high, the structure is complex, and the cable cost
										  is more than three times that of the DC cable. That's why the DC 
										  Cable of SSI Cables and wires is the best and has the best quality 
										  standards. SSI Cables and Wires DC Cable is the best in INDIA.</p>
                                <!-- <p style="text-align:justify"> The cables do not heat up and are also chiefly demanded in reactor & process control, navy sector, high-temperature control value furnace & oven.
                                </p> -->

                           
                        
                        

							</div>

			

                            
							<div class="col-md-12" style="padding-top: 30px;">
                            <center><img src="images/gallery/dc-cable.jpg" class="img-responsive" alt="DC Cable" style="width: 500px; height: 300px;"></center>
						

							</div>


						


							<div class="col-md-12">
								<center><a href="enquiry.php"><img src="images/product/enquiry.png" /></a></center>

							</div>





						</div>

					</div>

				</div>



			</div>

			<!-- //Block -->

		</div>

		<!-- // Content  -->
<?php include('footer.php'); ?>